apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  webproxy: false
  ingresses:
    - "https://syfomodiaperson.nais.preprod.local"
  env:
    - name: NAIS_CONTEXT
      value: 'dev'
    - name: NODE_ENV
      value: "production"
    - name: FASTLEGEREST_HOST
      value: "fastlegerest.dev.intern.nav.no"
    - name: FLEX_INTERN_GATEWAY_HOST
      value: "flex-intern-gateway.dev.intern.nav.no"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator-q0.dev.intern.nav.no"
    - name: ISDIALOGMOTE_HOST
      value: "isdialogmote.dev.intern.nav.no"
    - name: ISPENGESTOPP_HOST
      value: "ispengestopp.dev.intern.nav.no"
    - name: ISPERSONOPPGAVE_HOST
      value: "ispersonoppgave.dev.intern.nav.no"
    - name: ISPREDIKSJON_HOST
      value: "isprediksjon.dev.intern.nav.no"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder-q0.dev.adeo.no"
    - name: MODIASYFOREST_HOST
      value: "modiasyforest.dev.intern.nav.no"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "syfobehandlendeenhet.dev.intern.nav.no"
    - name: SYFOMOTEADMIN_HOST
      value: "syfomoteadmin.dev.intern.nav.no"
    - name: SYFOMOTEBEHOV_HOST
      value: "syfomotebehov.dev.intern.nav.no"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "syfooppfolgingsplanservice.dev.intern.nav.no"
    - name: SYFOPERSON_HOST
      value: "syfoperson.dev.intern.nav.no"
    - name: SYFOSMREGISTER_HOST
      value: "syfosmregister.dev.intern.nav.no"
    - name: SYFOSOKNAD_HOST
      value: "syfosoknad.dev.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_HOST
      value: "syfo-tilgangskontroll.dev.intern.nav.no"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.dev.intern.nav.no"

