apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  webproxy: false
  ingresses:
    - "https://syfomodiaperson.nais.adeo.no"
  env:
    - name: NAIS_CONTEXT
      value: 'prod'
    - name: NODE_ENV
      value: "production"
    - name: FASTLEGEREST_HOST
      value: "fastlegerest.intern.nav.no"
    - name: FLEX_INTERN_GATEWAY_HOST
      value: "flex-intern-gateway.intern.nav.no"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator.intern.nav.no"
    - name: ISDIALOGMOTE_HOST
      value: "isdialogmote.intern.nav.no"
    - name: ISPENGESTOPP_HOST
      value: "ispengestopp.intern.nav.no"
    - name: ISPERSONOPPGAVE_HOST
      value: "ispersonoppgave.intern.nav.no"
    - name: ISPREDIKSJON_HOST
      value: "isprediksjon.intern.nav.no"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder.nais.adeo.no"
    - name: MODIASYFOREST_HOST
      value: "modiasyforest.intern.nav.no"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "syfobehandlendeenhet.intern.nav.no"
    - name: SYFOMOTEADMIN_HOST
      value: "syfomoteadmin.intern.nav.no"
    - name: SYFOMOTEBEHOV_HOST
      value: "syfomotebehov.intern.nav.no"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "syfooppfolgingsplanservice.intern.nav.no"
    - name: SYFOPERSON_HOST
      value: "syfoperson.intern.nav.no"
    - name: SYFOSMREGISTER_HOST
      value: "syfosmregister.intern.nav.no"
    - name: SYFOSOKNAD_HOST
      value: "syfosoknad.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_HOST
      value: "syfo-tilgangskontroll.intern.nav.no"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.intern.nav.no"
